### ISSUE TITLE
Text Colors

### ISSUE THREAD

**Issue by Spock8901** [ntm5/cs2TTT#7]
This can be on the roadmap for later on just pinning it,
the word TTT when the countdown happens be red and the TTT plugin text can it all be green? just so that its more recognizable?
Like this:  
![image](https://github.com/ntm5/cs2TTT/assets/160471459/906dc37a-5654-4d77-9694-5b733b3bacc6)
had to use eGO forums to do the colors but yea almost like it

**Comment by ntm5** [comment]
It's coming!

**Comment by ntm5** [comment]
Fixed
